/* ============================================================
   بيانات المكتب — عدّل هذا الملف وحده لتحديث المحتوى
   ============================================================ */
window.STORE = {
  /* ---------- معلومات المكتب ---------- */
  info: {
    name: "مكتب سفيان للاتصالات",
    tagline: "هواتف • رصيد • إنترنت • صيانة",
    city: "سامراء — صلاح الدين",
    address: "صلاح الدين — سامراء — الحويش — الشارع الرئيسي",
    hours: "يوميًا من 9:00 صباحًا حتى 10:00 مساءً",
    phones: ["07731644450", "07744485771"],
    whatsapp: ["9647731644450", "9647744485771"],
    currency: "IQD",
    mapUrl: "https://maps.google.com/?q=Samarra+Al+Huwaysh",
  },

  /* ---------- الخدمات ---------- */
  services: [
    {
      icon: "bolt",
      title: "شحن رصيد فوري",
      desc: "آسياسيل، زين، كورك — الشحن خلال ثوانٍ وبكل الفئات، مع إشعار تأكيد.",
      cta: "اشحن الآن",
    },
    {
      icon: "wifi",
      title: "باقات إنترنت",
      desc: "اشتراكات شهرية بسرعات ثابتة وتغطية داخل سامراء، مع تركيب ومتابعة.",
      cta: "شوف الباقات",
    },
    {
      icon: "phone",
      title: "بيع الهواتف",
      desc: "أجهزة أصلية بكفالة الوكيل، أحدث الإصدارات وأسعار تنافسية بالدينار.",
      cta: "تصفّح المتجر",
    },
    {
      icon: "headphones",
      title: "إكسسوارات",
      desc: "شواحن سريعة، سماعات، جرابات، وواقيات شاشة لأغلب الموديلات.",
      cta: "اطلب إكسسوار",
    },
    {
      icon: "tools",
      title: "صيانة وبرمجة",
      desc: "تبديل شاشات وبطاريات، فك الحظر، تحديث أنظمة، ونقل البيانات.",
      cta: "احجز موعد",
    },
    {
      icon: "swap",
      title: "تحويل رصيد وبطاقات",
      desc: "تحويل بين الشبكات وبطاقات الألعاب والخدمات الرقمية بأسعار السوق.",
      cta: "تواصل معنا",
    },
  ],

  /* ---------- باقات الإنترنت ---------- */
  plans: [
    {
      id: "n1",
      size: "40GB",
      speed: "حتى 20 Mbps",
      monthly: 15000,
      yearly: 150000,
      best: false,
      perks: ["تركيب مجاني", "دعم فني يومي", "تفعيل خلال ساعة"],
    },
    {
      id: "n2",
      size: "100GB",
      speed: "حتى 40 Mbps",
      monthly: 25000,
      yearly: 250000,
      best: true,
      perks: ["تركيب مجاني", "راوتر بسعر مخفّض", "أولوية بالدعم", "تفعيل فوري"],
    },
    {
      id: "n3",
      size: "200GB",
      speed: "حتى 60 Mbps",
      monthly: 40000,
      yearly: 400000,
      best: false,
      perks: ["تركيب مجاني", "راوتر مزدوج النطاق", "دعم على مدار اليوم"],
    },
    {
      id: "n4",
      size: "لا محدود",
      speed: "حتى 100 Mbps",
      monthly: 60000,
      yearly: 600000,
      best: false,
      perks: ["مناسب للمكاتب والألعاب", "IP ثابت اختياري", "صيانة مجانية"],
    },
  ],

  /* ---------- فئات شحن الرصيد ---------- */
  topups: [
    { carrier: "آسياسيل", amounts: [5000, 10000, 25000, 50000] },
    { carrier: "زين العراق", amounts: [5000, 10000, 25000, 50000] },
    { carrier: "كورك تيليكوم", amounts: [5000, 10000, 25000, 50000] },
  ],

  /* ---------- الهواتف ---------- */
  phones: [
    {
      id: "p001",
      name: "Samsung Galaxy S24 Ultra",
      brand: "Samsung",
      cat: "phones",
      price: 1750000,
      stock: true,
      hot: true,
      hue: ["#5b6cff", "#131a33"],
      spec: "12GB • 256GB • كاميرا 200MP",
      specs: {
        الشاشة: "6.8 إنش AMOLED بمعدل 120Hz و QHD+",
        المعالج: "Snapdragon 8 Gen 3",
        الذاكرة: "12GB رام",
        التخزين: "256GB / 512GB",
        البطارية: "5000mAh مع شحن 45W",
        الكاميرا: "200MP خلفية / 12MP أمامية",
        النظام: "أندرويد 14 — One UI",
      },
      colors: ["#1c1c1e", "#8e8e93", "#6a5acd"],
      score: { gaming: 10, camera: 10, battery: 8, storage: 9 },
    },
    {
      id: "p002",
      name: "iPhone 15 Pro Max",
      brand: "Apple",
      cat: "phones",
      price: 2100000,
      stock: true,
      hot: true,
      hue: ["#c9c3ba", "#2b2822"],
      spec: "تيتانيوم • A17 Pro • 256GB",
      specs: {
        الشاشة: "6.7 إنش OLED بمعدل 120Hz",
        المعالج: "Apple A17 Pro",
        الذاكرة: "8GB رام",
        التخزين: "256GB / 512GB / 1TB",
        البطارية: "4441mAh مع شحن 27W",
        الكاميرا: "48MP خلفية / 12MP أمامية",
        النظام: "iOS 17",
      },
      colors: ["#b8b4ad", "#3b4a5c", "#1c1c1e"],
      score: { gaming: 10, camera: 10, battery: 7, storage: 10 },
    },
    {
      id: "p011",
      name: "iPhone 15",
      brand: "Apple",
      cat: "phones",
      price: 1250000,
      stock: true,
      hue: ["#7fb3ff", "#16233d"],
      spec: "A16 Bionic • 128GB • 48MP",
      specs: {
        الشاشة: "6.1 إنش OLED",
        المعالج: "Apple A16 Bionic",
        الذاكرة: "6GB رام",
        التخزين: "128GB / 256GB",
        البطارية: "3349mAh مع شحن 20W",
        الكاميرا: "48MP خلفية / 12MP أمامية",
        النظام: "iOS 17",
      },
      colors: ["#8fbce6", "#f2c4d0", "#1c1c1e"],
      score: { gaming: 9, camera: 9, battery: 6, storage: 6 },
    },
    {
      id: "p003",
      name: "iPhone 13",
      brand: "Apple",
      cat: "phones",
      price: 900000,
      stock: true,
      hue: ["#e8e6e3", "#2a2a2e"],
      spec: "A15 Bionic • 128GB",
      specs: {
        الشاشة: "6.1 إنش OLED",
        المعالج: "Apple A15 Bionic",
        الذاكرة: "4GB رام",
        التخزين: "128GB / 256GB",
        البطارية: "3240mAh مع شحن 20W",
        الكاميرا: "12MP خلفية / 12MP أمامية",
        النظام: "iOS 17",
      },
      colors: ["#1c1c1e", "#f5f5f7", "#f2c4d0"],
      score: { gaming: 8, camera: 8, battery: 5, storage: 6 },
    },
    {
      id: "p004",
      name: "Samsung Galaxy A55",
      brand: "Samsung",
      cat: "phones",
      price: 520000,
      stock: true,
      hue: ["#4f7fe0", "#101a2e"],
      spec: "8GB • 128GB • AMOLED 120Hz",
      specs: {
        الشاشة: "6.6 إنش Super AMOLED بمعدل 120Hz",
        المعالج: "Exynos 1480",
        الذاكرة: "8GB رام",
        التخزين: "128GB / 256GB",
        البطارية: "5000mAh مع شحن 25W",
        الكاميرا: "50MP خلفية / 32MP أمامية",
        النظام: "أندرويد 14",
      },
      colors: ["#3b6fd4", "#d8e05a", "#1c1c1e"],
      score: { gaming: 6, camera: 7, battery: 8, storage: 7 },
    },
    {
      id: "p009",
      name: "Samsung Galaxy S23 FE",
      brand: "Samsung",
      cat: "phones",
      price: 780000,
      stock: false,
      hue: ["#7de8c3", "#12241f"],
      spec: "8GB • 128GB • كاميرا 50MP",
      specs: {
        الشاشة: "6.4 إنش AMOLED بمعدل 120Hz",
        المعالج: "Exynos 2200",
        الذاكرة: "8GB رام",
        التخزين: "128GB / 256GB",
        البطارية: "4500mAh مع شحن 25W",
        الكاميرا: "50MP خلفية / 10MP أمامية",
        النظام: "أندرويد 14",
      },
      colors: ["#7de8c3", "#8b6fd4", "#1c1c1e"],
      score: { gaming: 8, camera: 8, battery: 6, storage: 7 },
    },
    {
      id: "p005",
      name: "Xiaomi Redmi Note 13 Pro",
      brand: "Xiaomi",
      cat: "phones",
      price: 420000,
      stock: true,
      hue: ["#9b6cff", "#171331"],
      spec: "8GB • 256GB • شحن 67W",
      specs: {
        الشاشة: "6.67 إنش AMOLED بمعدل 120Hz",
        المعالج: "Snapdragon 7s Gen 2",
        الذاكرة: "8GB رام",
        التخزين: "256GB",
        البطارية: "5100mAh مع شحن 67W",
        الكاميرا: "200MP خلفية / 16MP أمامية",
        النظام: "أندرويد 13 — MIUI",
      },
      colors: ["#1c1c1e", "#8b6fd4", "#4caf7d"],
      score: { gaming: 6, camera: 8, battery: 9, storage: 8 },
    },
    {
      id: "p006",
      name: "Xiaomi Poco X6 Pro",
      brand: "Xiaomi",
      cat: "phones",
      price: 480000,
      stock: true,
      hot: true,
      hue: ["#ffd60a", "#2a2205"],
      spec: "12GB • 256GB • Dimensity 8300",
      specs: {
        الشاشة: "6.67 إنش AMOLED بمعدل 120Hz",
        المعالج: "Dimensity 8300 Ultra",
        الذاكرة: "12GB رام",
        التخزين: "256GB / 512GB",
        البطارية: "5000mAh مع شحن 67W",
        الكاميرا: "64MP خلفية / 16MP أمامية",
        النظام: "أندرويد 14 — HyperOS",
      },
      colors: ["#e8c84a", "#1c1c1e", "#8a8f99"],
      score: { gaming: 9, camera: 6, battery: 8, storage: 9 },
    },
    {
      id: "p007",
      name: "Infinix Note 40 Pro",
      brand: "Infinix",
      cat: "phones",
      price: 310000,
      stock: true,
      hue: ["#d4af6a", "#241c10"],
      spec: "8GB • 256GB • شحن 70W",
      specs: {
        الشاشة: "6.78 إنش AMOLED بمعدل 120Hz",
        المعالج: "Helio G99 Ultimate",
        الذاكرة: "8GB رام",
        التخزين: "256GB",
        البطارية: "5000mAh مع شحن 70W",
        الكاميرا: "108MP خلفية / 32MP أمامية",
        النظام: "أندرويد 14 — XOS",
      },
      colors: ["#d4af6a", "#4caf7d", "#1c1c1e"],
      score: { gaming: 5, camera: 6, battery: 9, storage: 8 },
    },
    {
      id: "p008",
      name: "Infinix Hot 40i",
      brand: "Infinix",
      cat: "phones",
      price: 165000,
      stock: true,
      hue: ["#5aa9ff", "#0f1c30"],
      spec: "8GB • 128GB • بطارية 5000",
      specs: {
        الشاشة: "6.56 إنش IPS بمعدل 90Hz",
        المعالج: "Unisoc T606",
        الذاكرة: "8GB رام",
        التخزين: "128GB / 256GB",
        البطارية: "5000mAh مع شحن 18W",
        الكاميرا: "50MP خلفية / 32MP أمامية",
        النظام: "أندرويد 13 — XOS",
      },
      colors: ["#3b6fd4", "#d4af6a", "#1c1c1e"],
      score: { gaming: 3, camera: 4, battery: 8, storage: 7 },
    },
    {
      id: "p012",
      name: "Samsung Galaxy A15",
      brand: "Samsung",
      cat: "phones",
      price: 185000,
      stock: true,
      hue: ["#6f8bff", "#131a33"],
      spec: "6GB • 128GB • AMOLED",
      specs: {
        الشاشة: "6.5 إنش Super AMOLED بمعدل 90Hz",
        المعالج: "Helio G99",
        الذاكرة: "6GB رام",
        التخزين: "128GB",
        البطارية: "5000mAh مع شحن 25W",
        الكاميرا: "50MP خلفية / 13MP أمامية",
        النظام: "أندرويد 14",
      },
      colors: ["#3b6fd4", "#e8c84a", "#1c1c1e"],
      score: { gaming: 4, camera: 5, battery: 8, storage: 5 },
    },
    {
      id: "p010",
      name: "Xiaomi Redmi 13C",
      brand: "Xiaomi",
      cat: "phones",
      price: 145000,
      stock: true,
      hue: ["#4ad6a0", "#0f2420"],
      spec: "6GB • 128GB • شاشة 6.74",
      specs: {
        الشاشة: "6.74 إنش IPS بمعدل 90Hz",
        المعالج: "Helio G85",
        الذاكرة: "6GB رام",
        التخزين: "128GB",
        البطارية: "5000mAh مع شحن 18W",
        الكاميرا: "50MP خلفية / 8MP أمامية",
        النظام: "أندرويد 13 — MIUI",
      },
      colors: ["#1c1c1e", "#3b6fd4", "#4caf7d"],
      score: { gaming: 3, camera: 4, battery: 8, storage: 5 },
    },
  ],

  /* ---------- الإكسسوارات ---------- */
  accessories: [
    {
      id: "a001",
      name: "شاحن Anker 65W GaN",
      brand: "Anker",
      cat: "chargers",
      price: 45000,
      stock: true,
      hue: ["#64d2ff", "#0e2233"],
      spec: "3 منافذ • شحن سريع PD",
      emoji: "⚡",
    },
    {
      id: "a002",
      name: "شاحن سيارة Baseus",
      brand: "Baseus",
      cat: "chargers",
      price: 20000,
      stock: true,
      hue: ["#8e8e93", "#1a1c22"],
      spec: "USB-C + USB-A",
      emoji: "🚗",
    },
    {
      id: "a003",
      name: "جراب iPhone 15 Pro سيليكون",
      brand: "Apple",
      cat: "cases",
      price: 12000,
      stock: true,
      hue: ["#ff9f0a", "#2b1c05"],
      spec: "حماية كاملة • ألوان متعددة",
      emoji: "🛡️",
    },
    {
      id: "a004",
      name: "جراب Galaxy S24 شفاف",
      brand: "Samsung",
      cat: "cases",
      price: 10000,
      stock: true,
      hue: ["#30d158", "#0d2416"],
      spec: "مضاد للصدمات • زوايا معزّزة",
      emoji: "🛡️",
    },
    {
      id: "a005",
      name: "سمّاعة AirPods Pro 2",
      brand: "Apple",
      cat: "audio",
      price: 340000,
      stock: true,
      hot: true,
      hue: ["#f5f5f7", "#2a2a2e"],
      spec: "عزل ضوضاء فعّال ANC",
      emoji: "🎧",
    },
    {
      id: "a006",
      name: "سمّاعة Redmi Buds 5",
      brand: "Xiaomi",
      cat: "audio",
      price: 38000,
      stock: true,
      hue: ["#5e5ce6", "#141233"],
      spec: "ANC • بطارية 40 ساعة",
      emoji: "🎧",
    },
    {
      id: "a007",
      name: "واقي شاشة زجاجي 9H",
      brand: "عام",
      cat: "screen",
      price: 7000,
      stock: true,
      hue: ["#64d2ff", "#0e2233"],
      spec: "يناسب أغلب الموديلات",
      emoji: "🔷",
    },
    {
      id: "a008",
      name: "واقي خصوصية Privacy",
      brand: "عام",
      cat: "screen",
      price: 12000,
      stock: false,
      hue: ["#bf5af2", "#22103a"],
      spec: "يمنع الرؤية الجانبية",
      emoji: "🔒",
    },
    {
      id: "a009",
      name: "باور بانك 20000mAh",
      brand: "Anker",
      cat: "chargers",
      price: 42000,
      stock: true,
      hue: ["#ffd60a", "#2a2205"],
      spec: "شحن سريع 22.5W • شاشة رقمية",
      emoji: "🔋",
    },
    {
      id: "a010",
      name: "ساعة ذكية Redmi Watch 4",
      brand: "Xiaomi",
      cat: "audio",
      price: 95000,
      stock: true,
      hue: ["#40cbe0", "#0d2429"],
      spec: "AMOLED • بطارية 20 يوم",
      emoji: "⌚",
    },
  ],

  /* ---------- تصنيفات المتجر ---------- */
  categories: [
    { id: "all", label: "الكل" },
    { id: "phones", label: "هواتف" },
    { id: "chargers", label: "شواحن" },
    { id: "audio", label: "صوتيات" },
    { id: "cases", label: "جرابات" },
    { id: "screen", label: "واقيات" },
  ],

  /* ---------- آراء الزبائن ---------- */
  voices: [
    {
      name: "أحمد الجبوري",
      role: "زبون دائم",
      stars: 5,
      text: "أفضل مكتب بسامراء. شحنت رصيد وطلبت جهاز، الخدمة سريعة والأسعار منافسة. التعامل محترم جدًا.",
    },
    {
      name: "مصطفى عبد الله",
      role: "صاحب محل",
      stars: 5,
      text: "ركّبوا لي باقة الإنترنت للمحل بنفس اليوم، والسرعة ثابتة طول الدوام. متابعة ممتازة بعد التركيب.",
    },
    {
      name: "زينب حسن",
      role: "طالبة جامعية",
      stars: 5,
      text: "اشتريت هاتف بسعر مناسب مع جراب وواقي شاشة هدية. شرحوا لي كل التفاصيل قبل الشراء.",
    },
    {
      name: "علي الدليمي",
      role: "موظف",
      stars: 4,
      text: "تبديل شاشة بنفس اليوم وبضمان. الصراحة شغل نظيف وسعر معقول مقارنة بغيرهم.",
    },
    {
      name: "عمر ياسين",
      role: "لاعب PUBG",
      stars: 5,
      text: "أشحن شدات وبطاقات من عندهم دائمًا، وصول فوري وما صار أي تأخير أبدًا.",
    },
  ],

  /* ---------- الأسئلة الشائعة ---------- */
  faq: [
    {
      q: "هل الأجهزة أصلية وعليها كفالة؟",
      a: "نعم، جميع الأجهزة أصلية وبكفالة الوكيل المعتمد. الكفالة تشمل عيوب التصنيع، ونسلّمك وصلًا رسميًا مع الجهاز.",
    },
    {
      q: "هل يوجد توصيل داخل سامراء؟",
      a: "نعم، التوصيل متاح داخل سامراء وضواحيها. الطلبات التي تتجاوز 250,000 دينار توصيل مجاني، وما دونها برسوم رمزية حسب المنطقة.",
    },
    {
      q: "كم يستغرق تفعيل باقة الإنترنت؟",
      a: "التفعيل عادة خلال ساعة إلى ساعتين من تأكيد الطلب، ويشمل التركيب وضبط الراوتر داخل المنزل أو المحل.",
    },
    {
      q: "هل أقدر أبدّل جهازي القديم؟",
      a: "نعم، نستقبل الأجهزة المستعملة بالتقييم الفوري ونحسب قيمتها من سعر الجهاز الجديد بعد فحصها.",
    },
    {
      q: "كيف أطلب من الموقع؟",
      a: "أضف ما تريد إلى السلة ثم اضغط زر الطلب — ينفتح واتساب برسالة جاهزة تحتوي تفاصيل طلبك، وترسلها لنا مباشرة.",
    },
    {
      q: "ما طرق الدفع المتاحة؟",
      a: "الدفع نقدًا في المكتب أو عند الاستلام، إضافة إلى التحويل عبر محافظ الدفع الإلكتروني المحلية.",
    },
  ],
};
